[[redirects]]
  from = "/blog/posts/react-clap-button"
  to = "/blog/posts/clap-button"
  status = 301

[[redirects]]
  from = "/blog/posts/like-clap-button-on-worpress"
  to = "/blog/posts/wordpress-like-button"
  status = 301
